# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\"\x18\n\x08HelloReq\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08HelloRes\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x06\x41\x64\x64Req\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x17\n\x06\x41\x64\x64Res\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32M\n\x0cHelloService\x12\"\n\x08SayHello\x12\t.HelloReq\x1a\t.HelloRes\"\x00\x12\x19\n\x03\x41\x64\x64\x12\x07.AddReq\x1a\x07.AddRes\"\x00\x62\x06proto3'
)




_HELLOREQ = _descriptor.Descriptor(
  name='HelloReq',
  full_name='HelloReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_HELLORES = _descriptor.Descriptor(
  name='HelloRes',
  full_name='HelloRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='HelloRes.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=73,
)


_ADDREQ = _descriptor.Descriptor(
  name='AddReq',
  full_name='AddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='AddReq.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='AddReq.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=105,
)


_ADDRES = _descriptor.Descriptor(
  name='AddRes',
  full_name='AddRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='AddRes.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['HelloReq'] = _HELLOREQ
DESCRIPTOR.message_types_by_name['HelloRes'] = _HELLORES
DESCRIPTOR.message_types_by_name['AddReq'] = _ADDREQ
DESCRIPTOR.message_types_by_name['AddRes'] = _ADDRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloReq = _reflection.GeneratedProtocolMessageType('HelloReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQ,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloReq)
  })
_sym_db.RegisterMessage(HelloReq)

HelloRes = _reflection.GeneratedProtocolMessageType('HelloRes', (_message.Message,), {
  'DESCRIPTOR' : _HELLORES,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:HelloRes)
  })
_sym_db.RegisterMessage(HelloRes)

AddReq = _reflection.GeneratedProtocolMessageType('AddReq', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQ,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:AddReq)
  })
_sym_db.RegisterMessage(AddReq)

AddRes = _reflection.GeneratedProtocolMessageType('AddRes', (_message.Message,), {
  'DESCRIPTOR' : _ADDRES,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:AddRes)
  })
_sym_db.RegisterMessage(AddRes)



_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=132,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='HelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQ,
    output_type=_HELLORES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='HelloService.Add',
    index=1,
    containing_service=None,
    input_type=_ADDREQ,
    output_type=_ADDRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
